CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
USER_ID INTEGER);

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
ADDRESS_ID INTEGER,
USER_ID INTEGER,
CAR_ID INTEGER);

CREATE TABLE CARS(
CAR_ID INTEGER PRIMARY KEY,
MAKE VARCHAR2(50),
CAR_MODEL VARCHAR2 (50),
CAR_YEAR INTEGER,
IS_OWNED VARCHAR2 (50),
CAR_VALUE INTEGER);

CREATE TABLE DEALER_USERS(
USER_ID INTEGER PRIMARY KEY,
USER_NAME VARCHAR2 (50),
DEALER_PASSWORD VARCHAR2 (50),
EMP_STATUS VARCHAR2 (50));

CREATE TABLE ADDRESSES(
ADDRESS_ID INTEGER PRIMARY KEY,
STREET_NAME VARCHAR2 (50),
CITY VARCHAR2 (50),
ZIP INTEGER);

--================================--
--==========ALTER TABLES==========--
--================================--

ALTER TABLE USER
ADD CONSTRAINT UQ_USER_ID
UNIQUE (USER_NAME);

-----FOREIGN KEYS-----
